//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SOUP.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.soupturboflex.SOUP;

/** @hidden */
public class _PlayerPrxI extends com.zeroc.Ice._ObjectPrxI implements PlayerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
