//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Soup.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Soup;

public interface MusicLibraryPrx extends com.zeroc.Ice.ObjectPrx
{
    default Song addSong(String title, String author, String type, String extension)
    {
        return addSong(title, author, type, extension, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song addSong(String title, String author, String type, String extension, java.util.Map<String, String> context)
    {
        return _iceI_addSongAsync(title, author, type, extension, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song> addSongAsync(String title, String author, String type, String extension)
    {
        return _iceI_addSongAsync(title, author, type, extension, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song> addSongAsync(String title, String author, String type, String extension, java.util.Map<String, String> context)
    {
        return _iceI_addSongAsync(title, author, type, extension, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_author -
     * @param iceP_type -
     * @param iceP_extension -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song> _iceI_addSongAsync(String iceP_title, String iceP_author, String iceP_type, String iceP_extension, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_author);
                     ostr.writeString(iceP_type);
                     ostr.writeString(iceP_extension);
                 }, istr -> {
                     Song ret;
                     ret = Song.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void addSongData(Song song, byte[] data, boolean finish)
    {
        addSongData(song, data, finish, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addSongData(Song song, byte[] data, boolean finish, java.util.Map<String, String> context)
    {
        _iceI_addSongDataAsync(song, data, finish, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addSongDataAsync(Song song, byte[] data, boolean finish)
    {
        return _iceI_addSongDataAsync(song, data, finish, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addSongDataAsync(Song song, byte[] data, boolean finish, java.util.Map<String, String> context)
    {
        return _iceI_addSongDataAsync(song, data, finish, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param iceP_data -
     * @param iceP_finish -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addSongDataAsync(Song iceP_song, byte[] iceP_data, boolean iceP_finish, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addSongData", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                     ostr.writeByteSeq(iceP_data);
                     ostr.writeBool(iceP_finish);
                 }, null);
        return f;
    }

    default void updateSong(Song song, boolean reset)
    {
        updateSong(song, reset, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void updateSong(Song song, boolean reset, java.util.Map<String, String> context)
    {
        _iceI_updateSongAsync(song, reset, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(Song song, boolean reset)
    {
        return _iceI_updateSongAsync(song, reset, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> updateSongAsync(Song song, boolean reset, java.util.Map<String, String> context)
    {
        return _iceI_updateSongAsync(song, reset, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param iceP_reset -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_updateSongAsync(Song iceP_song, boolean iceP_reset, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "updateSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                     ostr.writeBool(iceP_reset);
                 }, null);
        return f;
    }

    default void removeSong(Song song)
    {
        removeSong(song, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void removeSong(Song song, java.util.Map<String, String> context)
    {
        _iceI_removeSongAsync(song, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> removeSongAsync(Song song)
    {
        return _iceI_removeSongAsync(song, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> removeSongAsync(Song song, java.util.Map<String, String> context)
    {
        return _iceI_removeSongAsync(song, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_removeSongAsync(Song iceP_song, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "removeSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                 }, null);
        return f;
    }

    default Song[] searchWithText(String text)
    {
        return searchWithText(text, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Song[] searchWithText(String text, java.util.Map<String, String> context)
    {
        return _iceI_searchWithTextAsync(text, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Song[]> searchWithTextAsync(String text)
    {
        return _iceI_searchWithTextAsync(text, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Song[]> searchWithTextAsync(String text, java.util.Map<String, String> context)
    {
        return _iceI_searchWithTextAsync(text, context, false);
    }

    /**
     * @hidden
     * @param iceP_text -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Song[]> _iceI_searchWithTextAsync(String iceP_text, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Song[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchWithText", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_text);
                 }, istr -> {
                     Song[] ret;
                     ret = SongsHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default int playSong(Song song)
    {
        return playSong(song, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int playSong(Song song, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(song, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> playSongAsync(Song song)
    {
        return _iceI_playSongAsync(song, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> playSongAsync(Song song, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(song, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_playSongAsync(Song iceP_song, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     Song.ice_write(ostr, iceP_song);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default void stopSong(int port)
    {
        stopSong(port, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stopSong(int port, java.util.Map<String, String> context)
    {
        _iceI_stopSongAsync(port, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopSongAsync(int port)
    {
        return _iceI_stopSongAsync(port, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopSongAsync(int port, java.util.Map<String, String> context)
    {
        return _iceI_stopSongAsync(port, context, false);
    }

    /**
     * @hidden
     * @param iceP_port -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopSongAsync(int iceP_port, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stopSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_port);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicLibraryPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicLibraryPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicLibraryPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicLibraryPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MusicLibraryPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MusicLibraryPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MusicLibraryPrx.class, _MusicLibraryPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MusicLibraryPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MusicLibraryPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MusicLibraryPrx ice_adapterId(String newAdapterId)
    {
        return (MusicLibraryPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MusicLibraryPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MusicLibraryPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MusicLibraryPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MusicLibraryPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MusicLibraryPrx ice_invocationTimeout(int newTimeout)
    {
        return (MusicLibraryPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MusicLibraryPrx ice_connectionCached(boolean newCache)
    {
        return (MusicLibraryPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MusicLibraryPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MusicLibraryPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicLibraryPrx ice_secure(boolean b)
    {
        return (MusicLibraryPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MusicLibraryPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MusicLibraryPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicLibraryPrx ice_preferSecure(boolean b)
    {
        return (MusicLibraryPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MusicLibraryPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MusicLibraryPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MusicLibraryPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MusicLibraryPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MusicLibraryPrx ice_collocationOptimized(boolean b)
    {
        return (MusicLibraryPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MusicLibraryPrx ice_twoway()
    {
        return (MusicLibraryPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MusicLibraryPrx ice_oneway()
    {
        return (MusicLibraryPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MusicLibraryPrx ice_batchOneway()
    {
        return (MusicLibraryPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MusicLibraryPrx ice_datagram()
    {
        return (MusicLibraryPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MusicLibraryPrx ice_batchDatagram()
    {
        return (MusicLibraryPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MusicLibraryPrx ice_compress(boolean co)
    {
        return (MusicLibraryPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MusicLibraryPrx ice_timeout(int t)
    {
        return (MusicLibraryPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MusicLibraryPrx ice_connectionId(String connectionId)
    {
        return (MusicLibraryPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MusicLibraryPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MusicLibraryPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Soup::MusicLibrary";
    }
}
