//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Soup.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Soup;

public class Song implements java.lang.Cloneable,
                             java.io.Serializable
{
    public int id;

    public String title;

    public String author;

    public String extension;

    public String type;

    public float accuracy;

    public Song()
    {
        this.title = "";
        this.author = "";
        this.extension = "";
        this.type = "";
    }

    public Song(int id, String title, String author, String extension, String type, float accuracy)
    {
        this.id = id;
        this.title = title;
        this.author = author;
        this.extension = extension;
        this.type = type;
        this.accuracy = accuracy;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Song r = null;
        if(rhs instanceof Song)
        {
            r = (Song)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.title != r.title)
            {
                if(this.title == null || r.title == null || !this.title.equals(r.title))
                {
                    return false;
                }
            }
            if(this.author != r.author)
            {
                if(this.author == null || r.author == null || !this.author.equals(r.author))
                {
                    return false;
                }
            }
            if(this.extension != r.extension)
            {
                if(this.extension == null || r.extension == null || !this.extension.equals(r.extension))
                {
                    return false;
                }
            }
            if(this.type != r.type)
            {
                if(this.type == null || r.type == null || !this.type.equals(r.type))
                {
                    return false;
                }
            }
            if(this.accuracy != r.accuracy)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Soup::Song");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, title);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, author);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, extension);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, accuracy);
        return h_;
    }

    public Song clone()
    {
        Song c = null;
        try
        {
            c = (Song)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.title);
        ostr.writeString(this.author);
        ostr.writeString(this.extension);
        ostr.writeString(this.type);
        ostr.writeFloat(this.accuracy);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.title = istr.readString();
        this.author = istr.readString();
        this.extension = istr.readString();
        this.type = istr.readString();
        this.accuracy = istr.readFloat();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Song v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Song ice_read(com.zeroc.Ice.InputStream istr)
    {
        Song v = new Song();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Song> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Song v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Song> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Song.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Song _nullMarshalValue = new Song();

    /** @hidden */
    public static final long serialVersionUID = 783836835L;
}
